void set_vcyl(int cylnum, int state);
void pump_on();
void pump_off();
void power_on();
void power_off();
void air_on();
void air_off();
void spare_on();
void spare_off();
int horiz(int dir, unsigned short mag);
